<?php

namespace Bairro\Entity\Bairro;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Repository extends \Doctrine\ORM\EntityRepository
{
}
